### ISSUE TITLE
Question about the project status

### ISSUE THREAD

**Issue by arianmaykon** [owenmorris/chandler#1]
Question, is this a fork/update of the Chandler project (http://chandlerproject.org/)?
The project looks abandoned, last updated was in 2009.

**Comment by owenmorris** [comment]
Yes, that is the plan.  Please see [this mailing list post](http://lists.osafoundation.org/pipermail/chandler-dev/2015-April/010698.html) for more info.

**Comment by arianmaykon** [comment]
Thanks, hope to see great updates soon, the open source community miss a great tool like this, a kind of replacement for things like Evernote.

Cheers.

**Comment by justingoldberg** [comment]
@arianmaykon You might like highlighter.com. It's the future.
